<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Answer' => 'Odpoveď',
    'Create Faq Group' => 'Vytvor Faq skupinu',
    'Create Faq Q&A' => 'Vytvor Faq Q&A',
    'Created At' => 'Vytvorené',
    'Created By' => 'Vytvoril',
    'Enabled' => 'Zapnuté',
    'Faq Groups' => 'Faq skupiny',
    'Faq Q&A' => 'Faq Q&A',
    'Group' => 'Skupina',
    'Item deletion successful.' => 'Odstránenie položky bolo úspešné.',
    'ID' => 'ID',
    'Language Code (eg. en, sk)' => 'Kód jazyka (napr. en, sk)',
    'Name' => 'Názov',
    'Question' => 'Otázka',
    'The requested group can not be deleted. Delete related answers first.' => 'Požadovaná skupina nemože byť zmazaná. Najprv zmažte zodpovedajúce odpovede.',
    'Update Faq Group' => 'Uprav Faq skupinu',
    'Update Faq Q&A' => '',
    'Updated At' => 'Upravené',
    'Updated By' => 'Upravil',
    'Url (ommit statring /)' => 'Url (bez začiatočného /)',
];
